### ISSUE TITLE
Тема для обговорення

### ISSUE THREAD

**Issue by bob-byte** [bob-byte/Practical4GroupA#1]
Існує пропозиція про поїздку в Кам'янець-Подільський

**Comment by bob-byte** [comment]
Там є можливість екскурсії на повітряних кулях

**Comment by bob-byte** [comment]
Пишіть згоди або пропозиції

**Comment by VytvytskaSasha** [comment]
Я згідна з цією пропозицією

**Comment by nadia-aaa** [comment]
Мені подобається ця пропозиція, я згідна!
