### ISSUE TITLE
Розподілення роботи

### ISSUE THREAD

**Issue by bob-byte** [bob-byte/Practical4GroupA#2]
Можливість зголошення до роботи існує до 13.04 17:00

**Comment by bob-byte** [comment]
Ви зголошені, якщо увійшли в цей репозиторій до даного терміну

**Comment by bob-byte** [comment]
Щоб рівномірно було розподілено, ви виконуєте по два завдання, а я одне трохи більше

**Comment by bob-byte** [comment]
Беру дані про подорож

**Comment by bob-byte** [comment]
Решту між собою узгодьте

**Comment by nadia-aaa** [comment]
якщо ніхто не проти я беру ночівлю

**Comment by VytvytskaSasha** [comment]
я тоді харчування

**Comment by bob-byte** [comment]
Ще взагалі-то по 1 треба вибрати

**Comment by VytvytskaSasha** [comment]
і кошторис подорожі

**Comment by nadia-aaa** [comment]
ок, тоді я засоби комунікації
