### ISSUE TITLE
Дані про місце подорожі

### ISSUE THREAD

**Issue by bob-byte** [bob-byte/Practical4GroupA#3]

**Comment by bob-byte** [comment]
Хто бере і скількох батьків?

**Comment by VytvytskaSasha** [comment]
я + 3 чоловік

**Comment by nadia-aaa** [comment]
я і подруга

**Comment by bob-byte** [comment]
Закомітив файл "Важливі дані щодо добирання"

**Comment by bob-byte** [comment]
Закомітив маршрут окремим файлом

**Comment by bob-byte** [comment]
Закомітив файл "Найцікаві факти про Кам'янець-Подільський"

**Comment by bob-byte** [comment]
Закомітив файл "Захопливі заняття"

**Comment by bob-byte** [comment]
#No
