### ISSUE TITLE
Ночівля

### ISSUE THREAD

**Issue by bob-byte** [bob-byte/Practical4GroupA#4]

**Comment by nadia-aaa** [comment]
який варіант ночівлі  для вас кращий у хостелі чи готелі?

**Comment by bob-byte** [comment]
Готелі

**Comment by bob-byte** [comment]
Ви можете зробити себе відповідальними за проблему?

**Comment by VytvytskaSasha** [comment]
Готель

**Comment by nadia-aaa** [comment]
я хочу обрати фінансово вигідний і комфортний варіант для всіх

**Comment by bob-byte** [comment]
Тому ми беремо готелі

**Comment by bob-byte** [comment]
> Ви можете зробити себе відповідальними за проблему?
